const data = [
	{
		image: '/images/boy.png',
		animated: true,
		bg: 'city-rain-1.jpg',
		text: 'O ano era 2022, acho que Agosto...',
	},
	{
		image: '/images/boy.png',
		animated: false,
		bg: 'city-rain-1.jpg',
		text: 'Lembro do frio, da chuva...',
	},
	{
		image: '/images/boy.png',
		animated: false,
		bg: 'city-rain-1.jpg',
		text: 'Tínhamos tudo pra ficar em casa...',
	},
	{
		image: '/images/umbrella-girl.png',
		animated: true,
		bg: 'city-rain.jpg',
		text: 'E você aparece...',
	},
	{
		image: '/images/umbrella-girl.png',
		animated: false,
		bg: 'city-rain.jpg',
		text: 'Um metro e meio de graça e ternura...',
	},
	{
		image: '/images/umbrella-girl.png',
		animated: false,
		bg: 'city-rain.jpg',
		text: 'Que foram embora logo no início...',
	},
	{
		image: '/images/umbrella-girl.png',
		animated: false,
		bg: 'city-rain.jpg',
		text: 'Dando lugar a uma pedreirinha em potencial...',
	},
	{
		image: '/images/couple.png',
		animated: true,
		bg: 'bar.jpg',
		text: 'Por fora mostrávamos descontração...',
	},
	{
		image: '/images/couple.png',
		animated: false,
		bg: 'bar.jpg',
		text: 'A habilidade mútua para piadas infames...',
	},
	{
		image: '/images/black-three.gif',
		animated: true,
		bg: 'dark-forest.jpg',
		text: 'Mas o que nos uniu foi o que tínhamos por dentro...',
	},
	{
		image: '/images/black-three.gif',
		animated: false,
		bg: 'dark-forest.jpg',
		text: 'Muito diferentes, mas iguais nas coisas certas...',
	},
	{
		image: '/images/windrose.gif',
		animated: true,
		bg: 'sea.jpg',
		text: 'A vida ao seu lado trouxe uma série de emoções...',
	},
	{
		image: '/images/windrose.gif',
		animated: false,
		bg: 'sea.jpg',
		text: 'Discutimos...',
	},
	{
		image: '/images/windrose.gif',
		animated: false,
		bg: 'sea.jpg',
		text: 'Refletimos...',
	},
	{
		image: '/images/windrose.gif',
		animated: false,
		bg: 'sea.jpg',
		text: 'Aprendemos...',
	},
	{
		image: '/images/windrose.gif',
		animated: false,
		bg: 'sea.jpg',
		text: 'E continuamos aprendendo...',
	},
	{
		image: '/images/couple-1.png',
		animated: true,
		bg: 'farm.jpg',
		text: 'Tivemos dias incríveis...',
	},
	{
		image: '/images/couple-1.png',
		animated: false,
		bg: 'farm.jpg',
		text: 'É sério...',
	},
	{
		image: '/images/certification.png',
		animated: true,
		bg: 'college.jpg',
		text: 'Conquistas...',
	},
	{
		image: '/images/certification.png',
		animated: false,
		bg: 'college.jpg',
		text: 'Juntos...',
	},
	{
		image: '/images/winged-dog.png',
		animated: true,
		bg: 'heaven.jpg',
		text: 'Perdas...',
	},
	{
		image: '/images/winged-dog.png',
		animated: false,
		bg: 'heaven.jpg',
		text: 'Difíceis...',
	},
	{
		image: '/images/matilda.png',
		animated: true,
		bg: 'grass.jpg',
		text: 'Recomeços...',
	},
	{
		image: '/images/matilda.png',
		animated: true,
		bg: 'grass.jpg',
		text: 'Um tanto atropelados...',
	},
	{
		image: '/images/windrose.gif',
		animated: true,
		bg: 'sea.jpg',
		text: 'Quase tudo é incerto com a gente...',
	},
	{
		image: '/images/windrose.gif',
		animated: false,
		bg: 'sea.jpg',
		text: 'Mas a única certeza que eu tenho...',
	},
	{
		image: '/images/ifelse.png',
		animated: true,
		bg: 'tech.jpg',
		text: 'É que, mesmo que hajam muitas variáveis...',
	},
	{
		image: '/images/ifelse.png',
		animated: false,
		bg: 'tech.jpg',
		text: 'A constante é que no fim do dia, eu sempre te amo...',
	},
	{
		image: '/images/cvv.png',
		animated: true,
		bg: 'blue.jpg',
		text: 'Essa é a mensagem que nós, da CVV, desejamos a você...',
	},
	{
		image: '/images/cvv.png',
		animated: false,
		bg: 'blue.jpg',
		text: 'Brinks...',
	},
	{
		image: '/images/beating-heart.gif',
		animated: true,
		bg: 'love.jpg',
		text: 'Eu te amo...',
	},
	{
		image: '/images/beating-heart.gif',
		animated: false,
		bg: 'love.jpg',
		text: 'É sério...',
	},
	{
		image: '/images/beating-heart.gif',
		animated: false,
		bg: 'love.jpg',
		text: 'A CVV também te ama, a propósito...',
	},
	{
		image: '/images/beating-heart.gif',
		animated: false,
		bg: 'love.jpg',
		text: 'Mas eu amo mais...',
	},
	{
		image: '/images/beating-heart.gif',
		animated: false,
		bg: 'love.jpg',
		text: 'Olha que coração bonitinho...',
	},
	{
		image: '/images/beating-heart.gif',
		animated: false,
		bg: 'love.jpg',
		text: 'É isso... Bom trabalho e um excelente dia...',
	},
	{
		image: '/images/beating-heart.gif',
		animated: false,
		bg: 'love.jpg',
		text: 'PS: esqueci de lavar o fogão...',
		finish: true,
	},
	{
		image: '/images/dove.png',
		animated: true,
		bg: 'soccer.jpg',
		text: '#paznosestadios',
		finish: true,
	},
];

export default data;
